[package]
name = "day9"
version = "0.1.0"
authors = ["David Cournapeau <cournape@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
itertools = "^0.8.2"

